logging:
  config: classpath:log/logback.xml
spring:
  devtools:
    restart:
      enabled: true
server:
  tomcat:
    uri-encoding: UTF-8
ribbon:
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 3
  OkToRetryOnAllOperations: true
  ConnectTimeout: 1500
  ReadTimeout: 2000
