discovery:
  port: 8887
logging:
  config: classpath:log/logback.xml
spring:
  devtools:
    restart:
      enabled: false
server:
  tomcat:
    uri-encoding: UTF-8
eureka:
  instance:
    healthCheckUrlPath: ${server.context-path}/health
    statusPageUrlPath: ${server.context-path}/info   
    hostname: localhost
  dashboard:
    path: /
  client:
    serviceUrl:
       defaultZone: http://${eureka.instance.hostname}:${discovery.port}/discovery/eureka/  